clear @s
give @s yb:carrot_on_a_stick
give @s yb:cauldron
give @s yb:chain
give @s yb:chalkboard
give @s yb:charcoal
give @s yb:chest_boat
give @s yb:chestplate
give @s yb:chicken_cooked
give @s yb:chicken_raw
give @s yb:chorus_fruit
give @s yb:chorus_fruit_popped
give @s yb:clay_ball
give @s yb:clock_item
give @s yb:clownfish
give @s yb:coal
give @s yb:comparator
give @s yb:compass_item
give @s yb:cooked_fish
give @s yb:cooked_salmon
give @s yb:cookie
give @s yb:copper_ingot
give @s yb:crimson_door
give @s yb:crimson_sign_item
give @s yb:crossbow_pulling
give @s yb:crossbow_standby
give @s yb:dark_oak_door
give @s yb:diamond
give @s yb:diamond_horse_armor
give @s yb:disc_fragment_5
give @s yb:dragon_breath
give @s yb:dried_kelp
give @s yb:dye_powder
give @s yb:echo_shard
give @s yb:egg
give @s yb:egg_bee
give @s yb:elytra
