clear @s
give @s yb:acacia_door
give @s yb:amethyst_shard
give @s yb:apple
give @s yb:apple_golden
give @s yb:armor_stand
give @s yb:arrow
give @s yb:axe
give @s yb:banner_pattern
give @s yb:bed
give @s yb:beef_cooked
give @s yb:beef_raw
give @s yb:beetroot
give @s yb:beetroot_soup
give @s yb:birch_door
give @s yb:blaze_powder
give @s yb:blaze_rod
give @s yb:boat
give @s yb:bone
give @s yb:book_enchanted
give @s yb:book_normal
give @s yb:book_portfolio
give @s yb:book_writable
give @s yb:book_written
give @s yb:boots
give @s yb:bow_pulling
give @s yb:bow_standby
give @s yb:bowl
give @s yb:bread
give @s yb:brewing_stand
give @s yb:brick
give @s yb:bucket
give @s yb:cake
give @s yb:camera
give @s yb:campfire
give @s yb:carrot
give @s yb:carrot_golden
