clear @s
give @s yb:record_mellohi
give @s yb:record_otherside
give @s yb:record_pigstep
give @s yb:record_stal
give @s yb:record_strad
give @s yb:record_wait
give @s yb:record_ward
give @s yb:recovery_compass
give @s yb:redstone_dust
give @s yb:reeds
give @s yb:repeater
give @s yb:rotten_flesh
give @s yb:saddle
give @s yb:salmon
give @s yb:seeds_beetroot
give @s yb:seeds_melon
give @s yb:seeds_pumpkin
give @s yb:seeds_wheat
give @s yb:shears
give @s yb:shield
give @s yb:shovel
give @s yb:shulker_shell
give @s yb:sign
give @s yb:sign_acacia
give @s yb:sign_birch
give @s yb:sign_darkoak
give @s yb:sign_jungle
give @s yb:sign_spruce
give @s yb:slimeball
give @s yb:snowball
give @s yb:soul_campfire
give @s yb:spawn_egg
give @s yb:spawn_egg_bee
give @s yb:spawn_egg_wandering_trader
give @s yb:spider_eye
give @s yb:spider_eye_fermented
