clear @s
give @s yb:painting
give @s yb:paper
give @s yb:phantom_membrane
give @s yb:pickaxe
give @s yb:porkchop_cooked
give @s yb:porkchop_raw
give @s yb:potato
give @s yb:potato_baked
give @s yb:potato_poisonous
give @s yb:potion_bottle_drinkable
give @s yb:potion_bottle_empty
give @s yb:potion_bottle_lingering
give @s yb:potion_bottle_splash
give @s yb:potion_overlay
give @s yb:prismarine_crystals
give @s yb:prismarine_shard
give @s yb:pufferfish
give @s yb:pumpkin_pie
give @s yb:quartz
give @s yb:quiver
give @s yb:rabbit
give @s yb:rabbit_cooked
give @s yb:rabbit_foot
give @s yb:rabbit_hide
give @s yb:rabbit_stew
give @s yb:raw_copper
give @s yb:raw_gold
give @s yb:raw_iron
give @s yb:record_11
give @s yb:record_13
give @s yb:record_5
give @s yb:record_blocks
give @s yb:record_cat
give @s yb:record_chirp
give @s yb:record_far
give @s yb:record_mall
