clear @s
give @s yb:emerald
give @s yb:empty_armor_slot_boots
give @s yb:empty_armor_slot_chestplate
give @s yb:empty_armor_slot_helmet
give @s yb:empty_armor_slot_leggings
give @s yb:empty_armor_slot_shield
give @s yb:end_crystal
give @s yb:ender_eye
give @s yb:ender_pearl
give @s yb:experience_bottle
give @s yb:feather
give @s yb:fireball
give @s yb:fireworks
give @s yb:fireworks_charge
give @s yb:fish
give @s yb:fishing_rod
give @s yb:flint
give @s yb:flint_and_steel
give @s yb:flower_pot
give @s yb:ghast_tear
give @s yb:glow_berries
give @s yb:glow_item_frame
give @s yb:glowstone_dust
give @s yb:goat_horn
give @s yb:gold_horse_armor
give @s yb:gold_ingot
give @s yb:gold_nugget
give @s yb:gunpowder
give @s yb:hanging_roots
give @s yb:heart_of_the_sea
give @s yb:helmet
give @s yb:hoe
give @s yb:honey_bottle
give @s yb:honeycomb
give @s yb:hopper
give @s yb:iron_door
