clear @s
give @s yb:spruce_door
give @s yb:spyglass
give @s yb:stick
give @s yb:string
give @s yb:sugar
give @s yb:suspicious_stew
give @s yb:sweet_berries
give @s yb:sword
give @s yb:tipped_arrow
give @s yb:totem
give @s yb:trident
give @s yb:turtle_helmet
give @s yb:turtle_shell_piece
give @s yb:warped_door
give @s yb:warped_fungus_on_a_stick
give @s yb:warped_sign_item
give @s yb:wheat
give @s yb:wooden_door
