clear @s
give @s yb:iron_horse_armor
give @s yb:iron_ingot
give @s yb:iron_nugget
give @s yb:item_frame
give @s yb:jungle_door
give @s yb:kelp
give @s yb:lead
give @s yb:leather
give @s yb:leather_horse_armor
give @s yb:leggings
give @s yb:lever
give @s yb:lodestonecompass_item
give @s yb:magma_cream
give @s yb:mangrove_door
give @s yb:mangrove_sign
give @s yb:map_empty
give @s yb:map_filled
give @s yb:melon
give @s yb:melon_speckled
give @s yb:minecart_chest
give @s yb:minecart_command_block
give @s yb:minecart_furnace
give @s yb:minecart_hopper
give @s yb:minecart_normal
give @s yb:minecart_tnt
give @s yb:mushroom_stew
give @s yb:mutton_cooked
give @s yb:mutton_raw
give @s yb:name_tag
give @s yb:nautilus_shell
give @s yb:nether_sprouts
give @s yb:nether_star
give @s yb:nether_wart
give @s yb:netherbrick
give @s yb:netherite_ingot
give @s yb:netherite_scrap
