clear @s yb:acacia_door
clear @s yb:amethyst_shard
clear @s yb:apple
clear @s yb:apple_golden
clear @s yb:armor_stand
clear @s yb:arrow
clear @s yb:axe
clear @s yb:banner_pattern
clear @s yb:bed
clear @s yb:beef_cooked
clear @s yb:beef_raw
clear @s yb:beetroot
clear @s yb:beetroot_soup
clear @s yb:birch_door
clear @s yb:blaze_powder
clear @s yb:blaze_rod
clear @s yb:boat
clear @s yb:bone
clear @s yb:book_enchanted
clear @s yb:book_normal
clear @s yb:book_portfolio
clear @s yb:book_writable
clear @s yb:book_written
clear @s yb:boots
clear @s yb:bow_pulling
clear @s yb:bow_standby
clear @s yb:bowl
clear @s yb:bread
clear @s yb:brewing_stand
clear @s yb:brick
clear @s yb:bucket
clear @s yb:cake
clear @s yb:camera
clear @s yb:campfire
clear @s yb:carrot
clear @s yb:carrot_golden
clear @s yb:carrot_on_a_stick
clear @s yb:cauldron
clear @s yb:chain
clear @s yb:chalkboard
clear @s yb:charcoal
clear @s yb:chest_boat
clear @s yb:chestplate
clear @s yb:chicken_cooked
clear @s yb:chicken_raw
clear @s yb:chorus_fruit
clear @s yb:chorus_fruit_popped
clear @s yb:clay_ball
clear @s yb:clock_item
clear @s yb:clownfish
clear @s yb:coal
clear @s yb:comparator
clear @s yb:compass_item
clear @s yb:cooked_fish
clear @s yb:cooked_salmon
clear @s yb:cookie
clear @s yb:copper_ingot
clear @s yb:crimson_door
clear @s yb:crimson_sign_item
clear @s yb:crossbow_pulling
clear @s yb:crossbow_standby
clear @s yb:dark_oak_door
clear @s yb:diamond
clear @s yb:diamond_horse_armor
clear @s yb:disc_fragment_5
clear @s yb:dragon_breath
clear @s yb:dried_kelp
clear @s yb:dye_powder
clear @s yb:echo_shard
clear @s yb:egg
clear @s yb:egg_bee
clear @s yb:elytra
clear @s yb:emerald
clear @s yb:empty_armor_slot_boots
clear @s yb:empty_armor_slot_chestplate
clear @s yb:empty_armor_slot_helmet
clear @s yb:empty_armor_slot_leggings
clear @s yb:empty_armor_slot_shield
clear @s yb:end_crystal
clear @s yb:ender_eye
clear @s yb:ender_pearl
clear @s yb:experience_bottle
clear @s yb:feather
clear @s yb:fireball
clear @s yb:fireworks
clear @s yb:fireworks_charge
clear @s yb:fish
clear @s yb:fishing_rod
clear @s yb:flint
clear @s yb:flint_and_steel
clear @s yb:flower_pot
clear @s yb:ghast_tear
clear @s yb:glow_berries
clear @s yb:glow_item_frame
clear @s yb:glowstone_dust
clear @s yb:goat_horn
clear @s yb:gold_horse_armor
clear @s yb:gold_ingot
clear @s yb:gold_nugget
clear @s yb:gunpowder
clear @s yb:hanging_roots
clear @s yb:heart_of_the_sea
clear @s yb:helmet
clear @s yb:hoe
clear @s yb:honey_bottle
clear @s yb:honeycomb
clear @s yb:hopper
clear @s yb:iron_door
clear @s yb:iron_horse_armor
clear @s yb:iron_ingot
clear @s yb:iron_nugget
clear @s yb:item_frame
clear @s yb:jungle_door
clear @s yb:kelp
clear @s yb:lead
clear @s yb:leather
clear @s yb:leather_horse_armor
clear @s yb:leggings
clear @s yb:lever
clear @s yb:lodestonecompass_item
clear @s yb:magma_cream
clear @s yb:mangrove_door
clear @s yb:mangrove_sign
clear @s yb:map_empty
clear @s yb:map_filled
clear @s yb:melon
clear @s yb:melon_speckled
clear @s yb:minecart_chest
clear @s yb:minecart_command_block
clear @s yb:minecart_furnace
clear @s yb:minecart_hopper
clear @s yb:minecart_normal
clear @s yb:minecart_tnt
clear @s yb:mushroom_stew
clear @s yb:mutton_cooked
clear @s yb:mutton_raw
clear @s yb:name_tag
clear @s yb:nautilus_shell
clear @s yb:nether_sprouts
clear @s yb:nether_star
clear @s yb:nether_wart
clear @s yb:netherbrick
clear @s yb:netherite_ingot
clear @s yb:netherite_scrap
clear @s yb:painting
clear @s yb:paper
clear @s yb:phantom_membrane
clear @s yb:pickaxe
clear @s yb:porkchop_cooked
clear @s yb:porkchop_raw
clear @s yb:potato
clear @s yb:potato_baked
clear @s yb:potato_poisonous
clear @s yb:potion_bottle_drinkable
clear @s yb:potion_bottle_empty
clear @s yb:potion_bottle_lingering
clear @s yb:potion_bottle_splash
clear @s yb:potion_overlay
clear @s yb:prismarine_crystals
clear @s yb:prismarine_shard
clear @s yb:pufferfish
clear @s yb:pumpkin_pie
clear @s yb:quartz
clear @s yb:quiver
clear @s yb:rabbit
clear @s yb:rabbit_cooked
clear @s yb:rabbit_foot
clear @s yb:rabbit_hide
clear @s yb:rabbit_stew
clear @s yb:raw_copper
clear @s yb:raw_gold
clear @s yb:raw_iron
clear @s yb:record_11
clear @s yb:record_13
clear @s yb:record_5
clear @s yb:record_blocks
clear @s yb:record_cat
clear @s yb:record_chirp
clear @s yb:record_far
clear @s yb:record_mall
clear @s yb:record_mellohi
clear @s yb:record_otherside
clear @s yb:record_pigstep
clear @s yb:record_stal
clear @s yb:record_strad
clear @s yb:record_wait
clear @s yb:record_ward
clear @s yb:recovery_compass
clear @s yb:redstone_dust
clear @s yb:reeds
clear @s yb:repeater
clear @s yb:rotten_flesh
clear @s yb:saddle
clear @s yb:salmon
clear @s yb:seeds_beetroot
clear @s yb:seeds_melon
clear @s yb:seeds_pumpkin
clear @s yb:seeds_wheat
clear @s yb:shears
clear @s yb:shield
clear @s yb:shovel
clear @s yb:shulker_shell
clear @s yb:sign
clear @s yb:sign_acacia
clear @s yb:sign_birch
clear @s yb:sign_darkoak
clear @s yb:sign_jungle
clear @s yb:sign_spruce
clear @s yb:slimeball
clear @s yb:snowball
clear @s yb:soul_campfire
clear @s yb:spawn_egg
clear @s yb:spawn_egg_bee
clear @s yb:spawn_egg_wandering_trader
clear @s yb:spider_eye
clear @s yb:spider_eye_fermented
clear @s yb:spruce_door
clear @s yb:spyglass
clear @s yb:stick
clear @s yb:string
clear @s yb:sugar
clear @s yb:suspicious_stew
clear @s yb:sweet_berries
clear @s yb:sword
clear @s yb:tipped_arrow
clear @s yb:totem
clear @s yb:trident
clear @s yb:turtle_helmet
clear @s yb:turtle_shell_piece
clear @s yb:warped_door
clear @s yb:warped_fungus_on_a_stick
clear @s yb:warped_sign_item
clear @s yb:wheat
clear @s yb:wooden_door
clear @s yb:air